import { lazy } from "react";

const appsRegistry = [
  {
    id: "settings",
    title: "Configuración",
    icon: "/images/icons/icon-settings.webp",
    route: "/configuracion",
    component: lazy(() => import("../apps/Settings/Settings.jsx")),
    defaultSize: { width: 860, height: 560 },
    showOnDesktop: true,
    pinToTaskbar: true,
    pinToStartMenu: true,
  },
  {
    id: "explorer",
    title: "Explorador",
    icon: "/images/icons/icon-explorer.webp",
    route: "/explorador",
    component: lazy(() => import("../apps/Explorer/Explorer.jsx")),
    defaultSize: { width: 860, height: 560 },
    showOnDesktop: true,
    pinToTaskbar: false,
    pinToStartMenu: true,
  },
  {
    id: "calendar",
    title: "Calendario",
    icon: "/images/icons/icon-calendar.webp",
    route: "/calendario",
    component: lazy(() => import("../apps/Calendar/Calendar.jsx")),
    defaultSize: { width: 860, height: 560 },
    showOnDesktop: true,
    pinToTaskbar: false,
    pinToStartMenu: true,
  },
  {
    id: "photos",
    title: "Fotos",
    icon: "/images/icons/icon-photos.webp",
    route: "/fotos",
    component: lazy(() => import("../apps/Photos/Photos.jsx")),
    defaultSize: { width: 860, height: 560 },
    showOnDesktop: true,
    pinToTaskbar: false,
    pinToStartMenu: true,
  },

  // Subaplicaciones del Explorador — no aparecen en escritorio ni menús
  {
    id: "quienes-somos",
    title: "¿Quiénes Somos?",
    icon: "/images/icons/icon-quienes-somos.webp",
    route: "/quienes-somos",
    component: lazy(() => import("../apps/QuienesSomos/QuienesSomos.jsx")),
    defaultSize: { width: 860, height: 560 },
    showOnDesktop: false,
    pinToTaskbar: false,
    pinToStartMenu: false,
  },
  {
    id: "historia-ismac",
    title: "Historia Ismac",
    icon: "/images/icons/icon-historia-ismac.webp",
    route: "/historia-ismac",
    component: lazy(() => import("../apps/HistoriaIsmac/HistoriaIsmac.jsx")),
    defaultSize: { width: 860, height: 560 },
    showOnDesktop: false,
    pinToTaskbar: false,
    pinToStartMenu: false,
  },
  {
    id: "ubicacion-ismac",
    title: "Ubicación Ismac",
    icon: "/images/icons/icon-ubicacion-ismac.webp",
    route: "/ubicacion-ismac",
    component: lazy(() => import("../apps/UbicacionIsmac/UbicacionIsmac.jsx")),
    defaultSize: { width: 860, height: 560 },
    showOnDesktop: false,
    pinToTaskbar: false,
    pinToStartMenu: false,
  },
];

export default appsRegistry;
