import {
  IoMedkitOutline,
  IoFlashOutline,
  IoReceiptOutline,
  IoCodeSlashOutline,
  IoBriefcaseOutline,
  IoCarOutline,
  IoMegaphoneOutline,
  IoGlobeOutline,
  IoRestaurantOutline,
} from 'react-icons/io5';

export const CAREERS = [
  {
    id:    'enfermeria',
    label: 'Enfermería',
    icon:  IoMedkitOutline,
    colors: {
      primary:       '#bed62f',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(124, 139, 31, 0.92)',
    border:   'rgba(190, 214, 47, 0.25)',
    logo: null,
    mascot: null,
  },
  {
    id:    'electromecanica',
    label: 'Electro Mecánica',
    icon:  IoFlashOutline,
    colors: {
      primary:       '#6d6d6c',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(76, 76, 76, 0.92)',
    border:   'rgba(109, 109, 108, 0.25)',
    logo: null,
    mascot: null,
  },
  {
    id:    'tributacion',
    label: 'Tributación',
    icon:  IoReceiptOutline,
    colors: {
      primary:       '#b57913',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(115, 80, 10, 0.95)',
    border:   'rgba(181, 121, 19, 0.25)',
    logo: null,
    mascot: null,
  },
  {
    id:    'software',
    label: 'Desarrollo de Software',
    icon:  IoCodeSlashOutline,
    colors: {
      primary:       '#0d3996',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(8, 32, 110, 0.98)',
    border:   'rgba(13, 57, 150, 0.30)',
    logo: null,
    mascot: null,
  },
  {
    id:    'administracion',
    label: 'Administración',
    icon:  IoBriefcaseOutline,
    colors: {
      primary:       '#0d8b9b',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(8, 85, 100, 0.95)',
    border:   'rgba(13, 139, 155, 0.25)',
    logo: null,
    mascot: null,
  },
  {
    id:    'mecanica',
    label: 'Mecánica Automotriz',
    icon:  IoCarOutline,
    colors: {
      primary:       '#890f23',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(85, 8, 20, 0.98)',
    border:   'rgba(137, 15, 35, 0.30)',
    logo: null,
    mascot: null,
  },
  {
    id:    'marketing',
    label: 'Marketing',
    icon:  IoMegaphoneOutline,
    colors: {
      primary:       '#fd7f27',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(170, 70, 10, 0.95)',
    border:   'rgba(253, 127, 39, 0.25)',
    logo: null,
    mascot: null,
  },
  {
    id:    'comercio',
    label: 'Comercio Exterior',
    icon:  IoGlobeOutline,
    colors: {
      primary:       '#383578',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(30, 26, 80, 0.98)',
    border:   'rgba(56, 53, 120, 0.30)',
    logo: null,
    mascot: null,
  },
  {
    id:    'gastronomia',
    label: 'Gastronomía',
    icon:  IoRestaurantOutline,
    colors: {
      primary:       '#fe2708',
      secondary:     null,
      complementary: null,
    },
    titlebar: 'rgba(165, 20, 5, 0.98)',
    border:   'rgba(254, 39, 8, 0.30)',
    logo: null,
    mascot: null,
  },
];
