// PDFs van en /public/documents/<nombre>.pdf
// Videos usan URLs de embed (YouTube, Vimeo, etc.)

const EXPLORER_REGISTRY = [
  {
    id: "informacion",
    label: "Información",
    items: [
      {
        id: "quienes-somos",
        label: "¿Quiénes Somos?",
        type: "app",
        appId: "quienes-somos",
        icon: "/images/icons/icon-quienes-somos.png",
      },
      {
        id: "historia-ismac",
        label: "Historia Ismac",
        type: "app",
        appId: "historia-ismac",
        icon: "/images/icons/icon-historia-ismac.png",
      },
      {
        id: "nosotros-ismac",
        label: "Nosotros Ismac",
        type: "video",
        src: "https://player.vimeo.com/video/691163823?h=ead4c35efe&badge=0&autopause=0&player_id=0",
        icon: "/images/icons/icon-nosotros.png",
      },
      {
        id: "ubicacion-ismac",
        label: "Ubicación Ismac",
        type: "app",
        appId: "ubicacion-ismac",
        icon: "/images/icons/icon-ubicacion-ismac.png",
      },
    ],
  },
  {
    id: "aplicaciones",
    label: "Aplicaciones",
    items: [
      {
        id: "dantesga",
        label: "Dantesga",
        type: "link",
        href: "https://dantesga.com",
        icon: "/images/icons/icon-dantesga.png",
      },
    ],
  },
  {
    id: "producciones",
    label: "Producciones",
    items: [
      {
        id: "podcast-ismac",
        label: "Podcast Ismac",
        type: "link",
        href: "https://podcasters.spotify.com/pod/show/ismac",
        icon: "/images/icons/icon-podcast.png",
      },
    ],
  },
  {
    id: "normativas",
    label: "Normativas",
    items: [
      {
        id: "loes",
        label: "LOES",
        type: "pdf",
        src: "/documents/loes.pdf",
        icon: "/images/icons/icon-loes.png",
      },
      {
        id: "reglamento-faltas",
        label: "Reglamento de Faltas y Sanciones",
        type: "pdf",
        src: "/documents/reglamento-faltas.pdf",
        icon: "/images/icons/icon-reglamiento-faltas-sanciones.png",
      },
      {
        id: "ley-organica",
        label: "Reglamento Ley Orgánica Superior",
        type: "pdf",
        src: "/documents/ley-organica.pdf",
        icon: "/images/icons/icon-reglamiento-lo-superior.png",
      },
      {
        id: "constitucion",
        label: "Constitución de la República del Ecuador",
        type: "pdf",
        src: "/documents/constitucion.pdf",
        icon: "/images/icons/icon-constitucion-ecuador.png",
      },
      {
        id: "reglamento-academico",
        label: "Reglamento Régimen Académico",
        type: "pdf",
        src: "/documents/reglamento-academico.pdf",
        icon: "/images/icons/icon-r-regimen-academico.png",
      },
      {
        id: "codigo-etica",
        label: "Código de Ética",
        type: "pdf",
        src: "/documents/codigo-etica.pdf",
        icon: "/images/icons/icon-codigo-etica.png",
      },
      {
        id: "manual-interculturalidad",
        label: "Manual de Aplicación del Principio de Interculturalidad",
        type: "pdf",
        src: "/documents/manual-interculturalidad.pdf",
        icon: "/images/icons/icon-manual-ap-interculturalidad.png",
      },
      {
        id: "plan-igualdad",
        label: "Plan de Igualdad Ismac",
        type: "pdf",
        src: "/documents/plan-igualdad.pdf",
        icon: "/images/icons/icon-plan-igualdad.png",
      },
      {
        id: "politicas-datos",
        label: "Políticas de Tratamiento de Datos",
        type: "pdf",
        src: "/documents/politicas-datos.pdf",
        icon: "/images/icons/icon-p-traramiento-datos.png",
      },
      {
        id: "manual-funciones",
        label: "Manual de Funciones Instituto Ismac",
        type: "pdf",
        src: "/documents/manual-funciones.pdf",
        icon: "/images/icons/icon-manual-funciones.png",
      },
      {
        id: "infraestructura",
        label: "Infraestructura",
        type: "pdf",
        src: "/documents/infraestructura.pdf",
        icon: "/images/icons/icon-infraestructura.png",
      },
      {
        id: "planificacion-estrategica",
        label: "Planificación Estratégica",
        type: "pdf",
        src: "/documents/planificacion-estrategica.pdf",
        icon: "/images/icons/icon-planificacion-estrategica.png",
      },
      {
        id: "relaciones-interinstitucionales",
        label: "Relaciones Interinstitucionales para el Desarrollo",
        type: "pdf",
        src: "/documents/relaciones-interinstitucionales.pdf",
        icon: "/images/icons/icon-relaciones-interinstitucionales.png",
      },
      {
        id: "aseguramiento-calidad",
        label: "Aseguramiento Interno de la Calidad",
        type: "pdf",
        src: "/documents/aseguramiento-calidad.pdf",
        icon: "/images/icons/icon-aseguramiento-calidad.png",
      },
      {
        id: "sistema-informatico",
        label: "Sistema Informático de Gestión",
        type: "pdf",
        src: "/documents/sistema-informatico.pdf",
        icon: "/images/icons/icon-sistema-informatico.png",
      },
      {
        id: "igualdad-oportunidades",
        label: "Igualdad de Oportunidades, No Discriminación e Igualdad",
        type: "pdf",
        src: "/documents/igualdad-oportunidades.pdf",
        icon: "/images/icons/icon-igualdad-oportunidades.png",
      },
      {
        id: "etica-transparencia",
        label: "Ética y Transparencia",
        type: "pdf",
        src: "/documents/etica-transparencia.pdf",
        icon: "/images/icons/icon-etica-transparencia.png",
      },
      {
        id: "profesores",
        label: "Profesores",
        type: "pdf",
        src: "/documents/profesores.pdf",
        icon: "/images/icons/icon-profesores.png",
      },
      {
        id: "formacion-capacitacion",
        label: "Formación y Capacitación",
        type: "pdf",
        src: "/documents/formacion-capacitacion.pdf",
        icon: "/images/icons/icon-formacion-capacitacion.png",
      },
      {
        id: "acompanamiento-pedagogico",
        label: "Acompañamiento Pedagógico",
        type: "pdf",
        src: "/documents/acompanamiento-pedagogico.pdf",
        icon: "/images/icons/icon-acompanamiento-pedagogico.png",
      },
      {
        id: "relacion-graduados",
        label: "Relación con los Graduados",
        type: "pdf",
        src: "/documents/relacion-graduados.pdf",
        icon: "/images/icons/icon-relacion-graduados.png",
      },
      {
        id: "entorno-virtual",
        label: "Entorno Virtual",
        type: "pdf",
        src: "/documents/entorno-virtual.pdf",
        icon: "/images/icons/icon-entorno-virtual.png",
      },
      {
        id: "formacion-valores",
        label: "Formación en Valores y Habilidades Blandas",
        type: "pdf",
        src: "/documents/formacion-valores.pdf",
        icon: "/images/icons/icon-formacion-valores.png",
      },
      {
        id: "formacion-practica",
        label: "Formación Práctica en el Entorno Académico y Laboral Real",
        type: "pdf",
        src: "/documents/formacion-practica.pdf",
        icon: "/images/icons/icon-formacion-practica.png",
      },
      {
        id: "biblioteca",
        label: "Biblioteca",
        type: "pdf",
        src: "/documents/biblioteca.pdf",
        icon: "/images/icons/icon-biblioteca.png",
      },
      {
        id: "investigacion-desarrollo",
        label: "Investigación, Desarrollo e Innovación",
        type: "pdf",
        src: "/documents/investigacion-desarrollo.pdf",
        icon: "/images/icons/icon-investigacion-desarrollo.png",
      },
      {
        id: "vinculacion-sociedad",
        label: "Vinculación con la Sociedad",
        type: "pdf",
        src: "/documents/vinculacion-sociedad.pdf",
        icon: "/images/icons/icon-vinculacion-sociedad.png",
      },
    ],
  },
  {
    id: "rendicion-cuentas",
    label: "Rendición de Cuentas",
    items: [
      {
        id: "rendicion-2022",
        label: "2022",
        type: "video",
        src: "",
        icon: "/images/icons/icon-reproductor.png",
      },
      {
        id: "rendicion-2023",
        label: "2023",
        type: "video",
        src: "",
        icon: "/images/icons/icon-reproductor.png",
      },
      {
        id: "rendicion-2024",
        label: "2024",
        type: "video",
        src: "",
        icon: "/images/icons/icon-reproductor.png",
      },
    ],
  },
  {
    id: "pedi-poa",
    label: "PEDI y POA",
    items: [
      {
        id: "pedi-2023-2028",
        label: "PEDI 2023 – 2028 Aprobado",
        type: "pdf",
        src: "/documents/pedi-2023-2028.pdf",
        icon: "/images/icons/icon-pdf.png",
      },
      {
        id: "poa-2024",
        label: "Plan Operativo Anual 2024 SF",
        type: "pdf",
        src: "/documents/poa-2024.pdf",
        icon: "/images/icons/icon-pdf.png",
      },
      {
        id: "poa-2023",
        label: "Plan Operativo Anual 2023 SF",
        type: "pdf",
        src: "/documents/poa-2023.pdf",
        icon: "/images/icons/icon-pdf.png",
      },
    ],
  },
  {
    id: "politica-calidad",
    label: "Política de Calidad",
    items: [
      {
        id: "politica-calidad-ismac",
        label: "Política de Calidad Ismac",
        type: "pdf",
        src: "/documents/politica-calidad.pdf",
        icon: "/images/icons/icon-pdf.png",
      },
    ],
  },
];

export default EXPLORER_REGISTRY;
